export interface Test {
  _id?: string; // id generated by MongoDB
  notes?: string;
  completedAt?: Date;
  createdAt?: Date;
  updatedAt?: Date;
  elapsed_time?: number;
  questions: Question[];

  // Resolved by the server through the flashcards of the questions, not stored
  // on the test. topic_name is only set when every question shares one topic.
  subject_name?: string;
  topic_name?: string | null;
}

export type Question = {
  flashcard_id: string;
  is_correct?: boolean;
}

export interface TestStats {
  totalTests: number;
  completedTests: number;
  totalTimeSpentSeconds: number;
  averageScorePercent: number;
}