export interface Test {
  _id?: string; // id generated by MongoDB
  notes?: string;
  completedAt?: Date;
  createdAt?: Date;
  updatedAt?: Date;
  elapsed_time?: number;
  questions: Question[];

  // Names resolved by the server from the subject and topic stored on the test.
  // topic_name is only set when every question of the test shares one topic.
  subject_name?: string;
  topic_name?: string | null;
}

export type Question = {
  flashcard_id: string;
  is_correct?: boolean;
  // The topic of the flashcard, stored on the question when the test is
  // created: it is what the review filters by, without reading the cards.
  topic_id?: string;
}

/**
 * One of the topics the questions of a test are on: what the review of a test
 * spanning several topics filters by.
 */
export interface TestTopic {
  _id: string;
  name: string;
  color?: string;
}

export interface TestStats {
  totalTests: number;
  completedTests: number;
  totalTimeSpentSeconds: number;
  averageScorePercent: number;
}