/** A test as it is read back: everything the server has resolved on it. */
export interface Test {
  _id?: string; // id generated by MongoDB
  notes?: string;
  completedAt?: Date;
  createdAt?: Date;
  updatedAt?: Date;
  elapsed_time?: number;
  questions: Question[];

  // Names resolved by the server from the subject and the topics stored on the
  // test. topic_names holds one name per topic the test touches.
  subject_name?: string;
  topic_names?: string[];

  // The test this one was built from (e.g. "repeat the wrong ones"), if any.
  parent_test_id?: string;

  // Set when the test was started from a community post instead of the
  // tester's own library: the runner reads it to send "exit" back to the
  // Community, and to ask first whether such a run is worth keeping.
  source_post_id?: string;
}

/**
 * A test as it is created: its questions, and nothing else. Everything a test
 * carries besides them - when it was taken, how long it took, what it is about -
 * is either decided by the server or set later, through the endpoint that owns
 * that one change.
 */
export interface TestCreateRequest {
  questions: Question[];
  parent_test_id?: string;
  source_post_id?: string;
}

export type Question = {
  flashcard_id: string;
  is_correct?: boolean;
  // The topic of the flashcard, stored on the question when the test is
  // created: it is what the review filters by, without reading the cards.
  topic_id?: string;
}

/**
 * One of the topics the questions of a test are on: what the review of a test
 * spanning several topics filters by.
 */
export interface TestTopic {
  _id: string;
  name: string;
  color?: string;
}

export interface TestStats {
  totalTests: number;
  completedTests: number;
  totalTimeSpentSeconds: number;
  averageScorePercent: number;
}